nelmio_api_doc:
    documentation:
        info:
            title: Meeting Room App - Backend
            description: Backend for the React Native app, written in Symfony 4
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
